### ISSUE TITLE
=dev-util/atom-shell-0.21.2-r1 : bootstrap failed

### ISSUE THREAD

**Issue by LMolr** [emcek/gentoo.mipl#4]
Can anyone install it successfully?
I get this error:

```
atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: _ZN2v87Isolate14ThrowExceptionENS_5LocalINS_5ValueEEE
```

All I find on internet about this symbol missing (`_ZN2v87Isolate14ThrowExceptionENS_5LocalINS_5ValueEEE`) is related to `Binary compatibility report for the V8 library  between 3.22.2 and 3.22.3 versions on x86`. I dont think it's relevant :-1:
#### Full error

```
>>> Preparing source in /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2 ...
 * Bootstrap atom-shell source
   - bootstrap: git submodule sync
   - bootstrap: git submodule update --init --recursive
   - bootstrap: npm install
   - bootstrap: /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/temp/python2.7/bin/python /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/brightray/script/bootstrap --commit 103778aa0ec3772f88e915ca9efdb941afdc85cf http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent
   - bootstrap: /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/temp/python2.7/bin/python /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/script/update.py
   - bootstrap: /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/.bin/apm install

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: _ZN2v87Isolate14ThrowExceptionENS_5LocalINS_5ValueEEE
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:359:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Traceback (most recent call last):
  File "./script/bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 35, in main
    update_atom_modules('spec')
  File "./script/bootstrap.py", line 77, in update_atom_modules
    execute_stdout([apm, 'install'])
  File "/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/script/lib/util.py", line 151, in execute_stdout
    execute(argv)
  File "/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/script/lib/util.py", line 139, in execute
    raise e
subprocess.CalledProcessError: Command '['/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/.bin/apm', 'install']' returned non-zero exit status 8
 * ERROR: dev-util/atom-shell-0.21.2-r1::emc failed (prepare phase):
 *   bootstrap failed
 *
 * Call stack:
 *     ebuild.sh, line  93:  Called src_prepare
 *   environment, line 3674:  Called die
 * The specific snippet of code:
 *       ./script/bootstrap.py || die "bootstrap failed";
 *
 * If you need support, post the output of `emerge --info '=dev-util/atom-shell-0.21.2-r1::emc'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/atom-shell-0.21.2-r1::emc'`.
 * The complete build log is located at '/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2'
 * S: '/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2'
```

**Comment by emcek** [comment]
@LMolr I was able to emerge this version. What atom-shell you had before? Maybe is irrelevant, but I want to know.

**Comment by LMolr** [comment]
Eix is telling me that I have `=dev-util/atom-shell-0.21.2(0/21)` (maybe because i am trying to emerge it).

```
[U] dev-util/atom-shell [1]
     Available versions:  (~)0.20.6(0/20) (~)0.21.2-r1(0/21) (~)9999(0/21) {debug}
     Installed versions:  0.21.2(0/21)(10:44:20 AM 02/10/2015)(-debug)
     Homepage:            https://github.com/atom/atom-shell
     Description:         Cross-platform desktop application shell

[1] "emc" /var/lib/layman/emc
```

**Comment by emcek** [comment]
**Installed version** is one it was successful installed. Try: `genlop -gti dev-util/atom-shell`

**Comment by LMolr** [comment]
``` ShellSession
$ sudo genlop -gti dev-util/atom-shell
 * dev-util/atom-shell

     Tue Feb 10 09:44:24 2015 >>> dev-util/atom-shell-0.21.2
       merge time: 11 minutes and 50 seconds.


   Total builds: 1
   Global build time: 11 minutes and 50 seconds.

   Info about currently installed ebuild:

   * dev-util/atom-shell-0.21.2
   Install date: Tue Feb 10 09:44:24 2015
   USE=" -debug"
   CFLAGS="-O2 -pipe -march=native   CXXFLAGS="-O2 -pipe -march=native   LDFLAGS="-Wl,-O1 -Wl,--as-needed"
```

**Comment by LMolr** [comment]
I am trying to emerge it with `USE="-debug"` and it looks like it's working..

**Comment by emcek** [comment]
- Do you have elogs from this merge? If you have enable in in `make.conf` Should be in **/var/log/portage/(elog)**
- can you unmerge (`emerge -C dev-util/atom-shell`) and try emerge once more?

**Comment by LMolr** [comment]
I have `build.log` :

```
❯ sudo cat /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/temp/build.log
 * Package:    dev-util/atom-shell-0.21.2-r1
 * Repository: emc
 * Maintainer: mplichta@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox splitdebug userpriv usersandbox
>>> Unpacking source...
 * Fetching git://github.com/atom/atom-shell ...
git fetch git://github.com/atom/atom-shell +refs/tags/v0.21.2:refs/tags/v0.21.2
git symbolic-ref refs/git-r3/dev-util/atom-shell/0/__main__ refs/tags/v0.21.2
 * Fetching https://github.com/brightray/brightray.git ...
git fetch https://github.com/brightray/brightray.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/brightray/__main__ 312e229ff159a7585cc0d437593b8dc66722bef0
 * Fetching https://github.com/brightray/libchromiumcontent ...
git fetch https://github.com/brightray/libchromiumcontent --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/brightray/vendor/libchromiumcontent/__main__ 3f108160eded696b3e843c2fbb4e5e2ac696555e
 * Fetching https://github.com/svn2github/python-patch ...
git fetch https://github.com/svn2github/python-patch --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/brightray/vendor/libchromiumcontent/vendor/python-patch/__main__ a336a458016ced89aba90dfc3f4c8222ae3b1403
 * Fetching https://chromium.googlesource.com/chromium/tools/depot_tools.git ...
git fetch https://chromium.googlesource.com/chromium/tools/depot_tools.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/brightray/vendor/libchromiumcontent/vendor/depot_tools/__main__ e3a3fd45aa7f6c247d9e9ab0900164004294fc8d
 * Fetching https://github.com/svn2github/gyp ...
git fetch https://github.com/svn2github/gyp --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/brightray/vendor/gyp/__main__ 81cdff9bb79bff2fcfe51ba4637fe8ebdd4ffb7f
 * Fetching https://github.com/svn2github/sgss-mirror-google-styleguide ...
git fetch https://github.com/svn2github/sgss-mirror-google-styleguide --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/brightray/vendor/google-styleguide/__main__ 8025f5495c04f1cf9e0d65a0aaa97b58c304faf7
 * Fetching https://github.com/atom/node.git ...
git fetch https://github.com/atom/node.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/node/__main__ 9cd0fad904c3ebf0af0aeec2097cad3e039a7c6d
 * Fetching https://chromium.googlesource.com/chromium/tools/depot_tools.git ...
git fetch https://chromium.googlesource.com/chromium/tools/depot_tools.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/depot_tools/__main__ 4fa73b8ca6899bc69577932b80145a6bf07e4424
 * Fetching https://github.com/atom/chromium-breakpad.git ...
git fetch https://github.com/atom/chromium-breakpad.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/breakpad/__main__ 1e937567e92d2c3beed4556f3c68a4b0362b1e6d
 * Fetching https://chromium.googlesource.com/external/google-breakpad/src.git ...
git fetch https://chromium.googlesource.com/external/google-breakpad/src.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/breakpad/src/__main__ 353da535e9af783c1c3fe896b1b3dc56e75486af
 * Fetching https://github.com/zcbenz/native-mate.git ...
git fetch https://github.com/zcbenz/native-mate.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/native_mate/__main__ 1116a36c15ac3e65720cf12d38a3308f40f7ea58
 * Checking out git://github.com/atom/atom-shell to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2 ...
git checkout --quiet refs/tags/v0.21.2
GIT update -->
   repository:               git://github.com/atom/atom-shell
   at the commit:            b75bfe0e92c8860a634bb50a53f1333ae9f5806f
 * Checking out https://github.com/brightray/brightray.git to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/brightray ...
git checkout --quiet 312e229ff159a7585cc0d437593b8dc66722bef0
GIT update -->
   repository:               https://github.com/brightray/brightray.git
   at the commit:            312e229ff159a7585cc0d437593b8dc66722bef0
 * Checking out https://github.com/brightray/libchromiumcontent to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/brightray/vendor/libchromiumcontent ...
git checkout --quiet 3f108160eded696b3e843c2fbb4e5e2ac696555e
GIT update -->
   repository:               https://github.com/brightray/libchromiumcontent
   at the commit:            3f108160eded696b3e843c2fbb4e5e2ac696555e
 * Checking out https://github.com/svn2github/python-patch to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/brightray/vendor/libchromiumcontent/vendor/python-patch ...
git checkout --quiet a336a458016ced89aba90dfc3f4c8222ae3b1403
GIT update -->
   repository:               https://github.com/svn2github/python-patch
   at the commit:            a336a458016ced89aba90dfc3f4c8222ae3b1403
 * Checking out https://chromium.googlesource.com/chromium/tools/depot_tools.git to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/brightray/vendor/libchromiumcontent/vendor/depot_tools ...
git checkout --quiet e3a3fd45aa7f6c247d9e9ab0900164004294fc8d
GIT update -->
   repository:               https://chromium.googlesource.com/chromium/tools/depot_tools.git
   at the commit:            e3a3fd45aa7f6c247d9e9ab0900164004294fc8d
 * Checking out https://github.com/svn2github/gyp to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/brightray/vendor/gyp ...
git checkout --quiet 81cdff9bb79bff2fcfe51ba4637fe8ebdd4ffb7f
GIT update -->
   repository:               https://github.com/svn2github/gyp
   at the commit:            81cdff9bb79bff2fcfe51ba4637fe8ebdd4ffb7f
 * Checking out https://github.com/svn2github/sgss-mirror-google-styleguide to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/brightray/vendor/google-styleguide ...
git checkout --quiet 8025f5495c04f1cf9e0d65a0aaa97b58c304faf7
GIT update -->
   repository:               https://github.com/svn2github/sgss-mirror-google-styleguide
   at the commit:            8025f5495c04f1cf9e0d65a0aaa97b58c304faf7
 * Checking out https://github.com/atom/node.git to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/node ...
git checkout --quiet 9cd0fad904c3ebf0af0aeec2097cad3e039a7c6d
GIT update -->
   repository:               https://github.com/atom/node.git
   at the commit:            9cd0fad904c3ebf0af0aeec2097cad3e039a7c6d
 * Checking out https://chromium.googlesource.com/chromium/tools/depot_tools.git to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/depot_tools ...
git checkout --quiet 4fa73b8ca6899bc69577932b80145a6bf07e4424
GIT update -->
   repository:               https://chromium.googlesource.com/chromium/tools/depot_tools.git
   at the commit:            4fa73b8ca6899bc69577932b80145a6bf07e4424
 * Checking out https://github.com/atom/chromium-breakpad.git to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/breakpad ...
git checkout --quiet 1e937567e92d2c3beed4556f3c68a4b0362b1e6d
GIT update -->
   repository:               https://github.com/atom/chromium-breakpad.git
   at the commit:            1e937567e92d2c3beed4556f3c68a4b0362b1e6d
 * Checking out https://chromium.googlesource.com/external/google-breakpad/src.git to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/breakpad/src ...
git checkout --quiet 353da535e9af783c1c3fe896b1b3dc56e75486af
GIT update -->
   repository:               https://chromium.googlesource.com/external/google-breakpad/src.git
   at the commit:            353da535e9af783c1c3fe896b1b3dc56e75486af
 * Checking out https://github.com/zcbenz/native-mate.git to /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/native_mate ...
git checkout --quiet 1116a36c15ac3e65720cf12d38a3308f40f7ea58
GIT update -->
   repository:               https://github.com/zcbenz/native-mate.git
   at the commit:            1116a36c15ac3e65720cf12d38a3308f40f7ea58
>>> Source unpacked in /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work
>>> Preparing source in /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2 ...
 * Bootstrap atom-shell source
   - bootstrap: git submodule sync
   - bootstrap: git submodule update --init --recursive
   - bootstrap: npm install
   - bootstrap: /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/temp/python2.7/bin/python /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/vendor/brightray/script/bootstrap --commit 103778aa0ec3772f88e915ca9efdb941afdc85cf http://gh-contractor-zcbenz.s3.amazonaws.com/libchromiumcontent
   - bootstrap: /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/temp/python2.7/bin/python /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/script/update.py
   - bootstrap: /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/.bin/apm install

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: _ZN2v87Isolate14ThrowExceptionENS_5LocalINS_5ValueEEE
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:359:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Traceback (most recent call last):
  File "./script/bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 35, in main
    update_atom_modules('spec')
  File "./script/bootstrap.py", line 77, in update_atom_modules
    execute_stdout([apm, 'install'])
  File "/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/script/lib/util.py", line 151, in execute_stdout
    execute(argv)
  File "/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/script/lib/util.py", line 139, in execute
    raise e
subprocess.CalledProcessError: Command '['/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2/node_modules/.bin/apm', 'install']' returned non-zero exit status 8
 * ERROR: dev-util/atom-shell-0.21.2-r1::emc failed (prepare phase):
 *   bootstrap failed
 *
 * Call stack:
 *     ebuild.sh, line  93:  Called src_prepare
 *   environment, line 3674:  Called die
 * The specific snippet of code:
 *       ./script/bootstrap.py || die "bootstrap failed";
 *
 * If you need support, post the output of `emerge --info '=dev-util/atom-shell-0.21.2-r1::emc'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/atom-shell-0.21.2-r1::emc'`.
 * The complete build log is located at '/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2'
 * S: '/var/tmp/portage/dev-util/atom-shell-0.21.2-r1/work/atom-shell-0.21.2'
```

I now try unmerge / merge ..

**Comment by LMolr** [comment]
Unmerging / merging results in the same error :(

**Comment by emcek** [comment]
I ment log from:

> ```
> Tue Feb 10 09:44:24 2015 >>> dev-util/atom-shell-0.21.2
>   merge time: 11 minutes and 50 seconds.
> ```

**Comment by LMolr** [comment]
No luck. On elog i have in time order:

```
>>> Messages generated by process 23025 on 2015-02-09 21:55:28 CET for package www-client/firefox-bin-31.3.0:
...
>>> Messages generated by process 13714 on 2015-02-10 11:12:35 CET for package app-editors/atom-0.177.0:
```

I will try to investigate further, in the meanwhile many thanks for your time (and overlay ofc!) ..

**Comment by emcek** [comment]
I can't reproduce http://pastebin.com/DvdHei1c

**Comment by emcek** [comment]
@LMolr can you try one of these...

**Comment by emcek** [comment]
and show me:

```
$ eix -I nodejs
$ npm --version
```

**Comment by LMolr** [comment]
It looks like there's something wrong with ebuilds.

# 0.21.0

``` ShellSession
sudo cat /var/tmp/portage/dev-util/atom-shell-0.21.0/temp/build.log
 * Package:    dev-util/atom-shell-0.21.0
 * Repository: emc
 * Maintainer: mplichta@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox splitdebug userpriv usersandbox
>>> Unpacking source...
 * Fetching git://github.com/atom/atom-shell ...
git fetch git://github.com/atom/atom-shell +refs/tags/v0.21.0:refs/tags/v0.21.0
git symbolic-ref refs/git-r3/dev-util/atom-shell/0/__main__ refs/tags/v0.21.0
 * Fetching https://github.com/brightray/brightray.git ...
git fetch https://github.com/brightray/brightray.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/brightray/__main__ c96ee1ee1e2d1322c4d73be18f28c232587a43a2
error: Trying to write ref refs/git-r3/dev-util/atom-shell/0/vendor/brightray/__main__ with nonexistent object c96ee1ee1e2d1322c4d73be18f28c232587a43a2
fatal: Cannot update the ref 'refs/git-r3/dev-util/atom-shell/0/vendor/brightray/__main__'.
 * ERROR: dev-util/atom-shell-0.21.0::emc failed (unpack phase):
 *   Referencing c96ee1ee1e2d1322c4d73be18f28c232587a43a2 failed (wrong ref?).
 *
 * Call stack:
 *     ebuild.sh, line   93:  Called src_unpack
 *   environment, line 3655:  Called git-r3_src_unpack
 *   environment, line 2076:  Called git-r3_src_fetch
 *   environment, line 2070:  Called git-r3_fetch
 *   environment, line 2011:  Called git-r3_fetch 'https://github.com/brightray/brightray.git' 'c96ee1ee1e2d1322c4d73be18f28c232587a43a2' 'dev-util/atom-shell/0/vendor/brightray'
 *   environment, line 1987:  Called die
 * The specific snippet of code:
 *                   die "Referencing ${remote_ref} failed (wrong ref?).";
 *
 * If you need support, post the output of `emerge --info '=dev-util/atom-shell-0.21.0::emc'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/atom-shell-0.21.0::emc'`.
 * The complete build log is located at '/var/tmp/portage/dev-util/atom-shell-0.21.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-util/atom-shell-0.21.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-util/atom-shell-0.21.0/work'
 * S: '/var/tmp/portage/dev-util/atom-shell-0.21.0/work/atom-shell-0.21.0'
```

# 0.21.1

``` ShellSession
$ sudo cat /var/tmp/portage/dev-util/atom-shell-0.21.1/temp/build.log
 * Package:    dev-util/atom-shell-0.21.1
 * Repository: emc
 * Maintainer: mplichta@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox splitdebug userpriv usersandbox
>>> Unpacking source...
 * Fetching git://github.com/atom/atom-shell ...
git fetch git://github.com/atom/atom-shell +refs/tags/v0.21.1:refs/tags/v0.21.1
git symbolic-ref refs/git-r3/dev-util/atom-shell/0/__main__ refs/tags/v0.21.1
 * Fetching https://github.com/brightray/brightray.git ...
git fetch https://github.com/brightray/brightray.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/dev-util/atom-shell/0/vendor/brightray/__main__ c96ee1ee1e2d1322c4d73be18f28c232587a43a2
error: Trying to write ref refs/git-r3/dev-util/atom-shell/0/vendor/brightray/__main__ with nonexistent object c96ee1ee1e2d1322c4d73be18f28c232587a43a2
fatal: Cannot update the ref 'refs/git-r3/dev-util/atom-shell/0/vendor/brightray/__main__'.
 * ERROR: dev-util/atom-shell-0.21.1::emc failed (unpack phase):
 *   Referencing c96ee1ee1e2d1322c4d73be18f28c232587a43a2 failed (wrong ref?).
 *
 * Call stack:
 *     ebuild.sh, line   93:  Called src_unpack
 *   environment, line 3655:  Called git-r3_src_unpack
 *   environment, line 2076:  Called git-r3_src_fetch
 *   environment, line 2070:  Called git-r3_fetch
 *   environment, line 2011:  Called git-r3_fetch 'https://github.com/brightray/brightray.git' 'c96ee1ee1e2d1322c4d73be18f28c232587a43a2' 'dev-util/atom-shell/0/vendor/brightray'
 *   environment, line 1987:  Called die
 * The specific snippet of code:
 *                   die "Referencing ${remote_ref} failed (wrong ref?).";
 *
 * If you need support, post the output of `emerge --info '=dev-util/atom-shell-0.21.1::emc'`,
 * the complete build log and the output of `emerge -pqv '=dev-util/atom-shell-0.21.1::emc'`.
 * The complete build log is located at '/var/tmp/portage/dev-util/atom-shell-0.21.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-util/atom-shell-0.21.1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-util/atom-shell-0.21.1/work'
 * S: '/var/tmp/portage/dev-util/atom-shell-0.21.1/work/atom-shell-0.21.1'
```

**Comment by LMolr** [comment]
``` ShellSession
$ eix -I nodejs
[I] net-libs/nodejs
     Available versions:  (~)0.8.28^t 0.10.30^t (~)0.10.31^t (~)0.10.32^t (~)0.10.33^t (~)0.10.35^t (~)0.10.36^t [M](~)0.11.12^t [M](~)0.11.13^t [M](~)0.11.13-r1^t [M](~)0.11.14^t [M](~)0.11.15^t (~)0.12.0^t {+npm +snapshot}
     Installed versions:  0.12.0^t(10:27:04 AM 02/15/2015)(npm)
     Homepage:            http://nodejs.org/
     Description:         Evented IO for V8 Javascript
```

``` ShellSession
$ npm --version
2.5.1
```

**Comment by emcek** [comment]
I'm @work and can do verification if `0.21.0` and `0.20.1` fail with fetching with git.
- all three ebuild `0.21.0, 0.21.1` and `0.21.2-r1` are exactly the same, difference is only file name, which cause to install different atom-shell version.
- you have latest **nodejs** it can cause all the mess with `0.21.2-r1` in the first place. If you don't really need `nodejs-0.12.0` you can downgrade to stable on `0.10.30`
- other thing you can try clean up git repos somewhere in **distfiles** location, if I remember correctly default is `/usr/portage/distfiles/(e)git/...`

**Comment by LMolr** [comment]
With `=nodejs-0.10.30` the latest atom-shell merges successfully. Thank you very much for your time!!!

**Comment by emcek** [comment]
nice! cool it was so easy....
